# Generated by Django 5.0.6 on 2024-06-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kessy', '0002_recipe_image_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizers & Snacks', 'Appetizers & Snacks'), ('Beverages & Cocktails', 'Beverages & Cocktails'), ('Breads & Breakfasts', 'Breads & Breakfasts'), ('Cakes & Frostings', 'Cakes & Frostings'), ('Casseroles & Skillets', 'Casseroles & Skillets'), ('Condiments, Spreads & Relishes', 'Condiments, Spreads & Relishes'), ('Cookies & Candies', 'Cookies & Candies'), ('Desserts', 'Desserts'), ('Beef', 'Beef'), ('Bread', 'Bread'), ('Chicken', 'Chicken'), ('Fish & Seafood', 'Fish & Seafood'), ('Indian Food', 'Indian Food'), ('Italian Food', 'Italian Food'), ('Lamb', 'Lamb'), ('Main Course', 'Main Course'), ('Pasta', 'Pasta'), ('Pork', 'Pork'), ('Salads', 'Salads'), ('Soups', 'Soups')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
